### ISSUE TITLE
File Name stuck

### ISSUE THREAD

**Issue by makayasa** [iCrawl/discord-vscode#1001] opened 2021-04-14 00:25 UTC
The Rich Presence wont change the detail when i move to another File. The file name still remain as the first File I open, and wont change when i move to another file.

But, when i change the folder with my other project, it works just fine. When I change to another file, the Rich Presence showing the new File I'm on it.

is there any problem with my main project folder ?

**Comment by xiJulian** [comment] 2021-04-14 00:28
same problem here

**Comment by zredrum** [comment] 2021-04-14 02:27
Bump. Can reproduce on Macbook with Big Sur.

**Comment by ayad-nadeeb** [comment] 2021-04-14 11:12
Having the same problem, closing and re-opening vscode updates the presence's status but does nothing when changing files. File name is stuck with the first file opened or remains Idling when no file is open on startup.

**Comment by iCrawl** [comment] 2021-04-14 12:59
I tested and fixed this in v5.6.0 (whenever Microsoft decides to release it)

**Closed by iCrawl** 2021-04-14 12:59 UTC

**Comment by zredrum** [comment] 2021-04-14 13:51
can still reproduce with latest 5.6.0

**Comment by iCrawl** [comment] 2021-04-14 13:52
Do you guys have git installed?

**Comment by zredrum** [comment] 2021-04-14 14:00
Update for those of you who may still have this issue on 5.6.0: I spoke with Crawl & it seems to be an issue with git and the new button update to display the repository button on your Discord status. To fix it temporarily, you can switch your git repository off https or go to the extension settings and checking the box below:

![imgur](https://i.imgur.com/5hrXmf7.png)

**Comment by iCrawl** [comment] 2021-04-14 14:02
This should be fixed now for real in v5.6.1

**Comment by zredrum** [comment] 2021-04-14 14:39
Is fixed. Feel free to close

**Comment by makayasa** [comment] 2021-04-14 15:03
Thanks for the great work, appreciate it

**Comment by jacany** [comment] 2021-04-17 04:06
Encountered this problem while trying to repro #1009, and got the issue. Fixed in #1010
